/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    GameBoard: typeof import('./src/components/GameBoard.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    PlayerForm: typeof import('./src/components/PlayerForm.vue')['default']
    Score: typeof import('./src/components/Score.vue')['default']
    WelcomeModal: typeof import('./src/components/WelcomeModal.vue')['default']
  }
}
